name: 'rs-action'
description: 'Build and publish Rust code for Linux, Windows and macOS'
author: 'MidKnightXI'
inputs:
  target:
    description: 'Target platform for compilation'
    required: false
  cargo-toml-path:
    description: 'Path to the Cargo.toml file'
    required: false
  publish-release:
    description: 'Publish release with compiled artifacts'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
